version: "3"
services:
  app:
    container_name: settings-microapi
    restart: always
    build: .
    ports:
      - "5209:5207"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py